version: '3.8'

services:
  # =============
  # TRAEFIK - API GATEWAY (PRODUCTION)
  # =============
  traefik:
    image: traefik:v3.4
    container_name: breezy-traefik-prod
    restart: unless-stopped
    command:
      # API Dashboard en mode développement pour faciliter les tests
      - "--api.insecure=true"
      # Provider Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Provider de fichiers pour configuration dynamique
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      # Points d'entrée
      - "--entrypoints.web.address=:80"
      # Logs optimisés pour production
      - "--log.level=INFO"
      - "--accesslog=true"
    ports:
      - "8080:80"     # API Gateway sur port 8080 (comme en dev)
      - "8081:8080"   # Dashboard Traefik sur port 8081 (comme en dev)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik:/etc/traefik/dynamic:ro"
      - "./logs/traefik:/var/log/traefik"
    networks:
      - breezy-microservices-network

  # =============
  # DATABASES (PRODUCTION)
  # =============
  mongodb-auth:
    image: mongo:7.0
    container_name: breezy-mongodb-auth-prod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=breezy_auth
    volumes:
      - mongodb_auth_data:/data/db
      - ./backups:/backups
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Pas de ports exposés en production pour sécurité

  mongodb-user:
    image: mongo:7.0
    container_name: breezy-mongodb-user-prod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=breezy_users
    volumes:
      - mongodb_user_data:/data/db
      - ./backups:/backups
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb-post:
    image: mongo:7.0
    container_name: breezy-mongodb-post-prod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=breezy_posts
    volumes:
      - mongodb_post_data:/data/db
      - ./backups:/backups
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb-notification:
    image: mongo:7.0
    container_name: breezy-mongodb-notification-prod
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=breezy_notifications
    volumes:
      - mongodb_notification_data:/data/db
      - ./backups:/backups
    networks:
      - breezy-microservices-network    
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # =============
  # MICROSERVICES (PRODUCTION)
  # =============
  auth-service:
    build:
      context: ./microservices
      dockerfile: auth-service/docker/Dockerfile.prod
    image: breezy-auth-service:latest
    container_name: breezy-auth-service-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb-auth:27017/breezy_auth
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      mongodb-auth:
        condition: service_healthy
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth-api.entrypoints=web"
      - "traefik.http.routers.auth-api.service=auth-service"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/api/auth"
      - "traefik.http.routers.auth-api.middlewares=auth-stripprefix,api-chain-prod@file"

  user-service:
    build:
      context: ./microservices
      dockerfile: user-service/docker/Dockerfile.prod
    image: breezy-user-service:latest
    container_name: breezy-user-service-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb-user:27017/breezy_users
      - AUTH_SERVICE_URL=http://auth-service:3001
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      mongodb-user:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    volumes:
      - ./uploads/users:/app/uploads
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-api.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.user-api.entrypoints=web"
      - "traefik.http.routers.user-api.service=user-service"
      - "traefik.http.services.user-service.loadbalancer.server.port=3002"
      - "traefik.http.middlewares.user-stripprefix.stripprefix.prefixes=/api/users"
      - "traefik.http.routers.user-api.middlewares=user-stripprefix,api-chain-prod@file"

  post-service:
    build:
      context: ./microservices
      dockerfile: post-service/docker/Dockerfile.prod
    image: breezy-post-service:latest
    container_name: breezy-post-service-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb-post:27017/breezy_posts
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mongodb-post:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    volumes:
      - ./uploads/posts:/app/uploads
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.post-api.rule=PathPrefix(`/api/posts`)"
      - "traefik.http.routers.post-api.entrypoints=web"
      - "traefik.http.routers.post-api.service=post-service"
      - "traefik.http.services.post-service.loadbalancer.server.port=3003"
      - "traefik.http.middlewares.post-stripprefix.stripprefix.prefixes=/api/posts"
      - "traefik.http.routers.post-api.middlewares=post-stripprefix,api-chain-prod@file"

  notification-service:
    build:
      context: ./microservices
      dockerfile: notification-service/docker/Dockerfile.prod
    image: breezy-notification-service:latest
    container_name: breezy-notification-service-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGODB_URI=mongodb://mongodb-notification:27017/breezy_notifications
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - POST_SERVICE_URL=http://post-service:3003
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mongodb-notification:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification-api.rule=PathPrefix(`/api/notifications`)"
      - "traefik.http.routers.notification-api.entrypoints=web"
      - "traefik.http.routers.notification-api.service=notification-service"
      - "traefik.http.services.notification-service.loadbalancer.server.port=3004"
      - "traefik.http.middlewares.notification-stripprefix.stripprefix.prefixes=/api/notifications"
      - "traefik.http.routers.notification-api.middlewares=notification-stripprefix,api-chain-prod@file"

  # =============
  # SWAGGER AGGREGATOR (PRODUCTION)
  # =============
  swagger-aggregator:
    build:
      context: ./swagger-aggregator
      dockerfile: Dockerfile
    image: breezy-swagger-aggregator:latest
    container_name: breezy-swagger-aggregator-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3005
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - POST_SERVICE_URL=http://post-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
    depends_on:
      - auth-service
      - user-service
      - post-service
      - notification-service
    networks:
      - breezy-microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"
      # Route pour /docs
      - "traefik.http.routers.docs.rule=PathPrefix(`/docs`)"
      - "traefik.http.routers.docs.entrypoints=web"
      - "traefik.http.routers.docs.service=swagger-aggregator"
      - "traefik.http.services.swagger-aggregator.loadbalancer.server.port=3005"
      - "traefik.http.routers.docs.middlewares=web-chain-prod@file"
      # Route pour la racine / (page d'accueil)
      - "traefik.http.routers.root.rule=Path(`/`)"
      - "traefik.http.routers.root.entrypoints=web"
      - "traefik.http.routers.root.service=swagger-aggregator"
      - "traefik.http.routers.root.priority=1"
      - "traefik.http.routers.root.middlewares=web-chain-prod@file"

  # =============
  # MONITORING & LOGGING (optionnel)
  # =============
  watchtower:
    image: containrrr/watchtower
    container_name: breezy-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    networks:
      - breezy-microservices-network

volumes:
  mongodb_auth_data:
    driver: local
  mongodb_user_data:
    driver: local
  mongodb_post_data:
    driver: local
  mongodb_notification_data:
    driver: local

networks:
  breezy-microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16